//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ACCOUNTID { get; set; }
        public string ACCOUNTNAME { get; set; }
        public string PASS { get; set; }
        public string MANV { get; set; }
    }
}
