//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYKYTUCEntities : DbContext
    {
        public QUANLYKYTUCEntities()
            : base("name=QUANLYKYTUCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_NHANVIEN> C_NHANVIEN { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<ROLEASSINGGROUP> ROLEASSINGGROUPs { get; set; }
        public virtual DbSet<ROLEGROUP> ROLEGROUPs { get; set; }
        public virtual DbSet<ROLEGROUPACCOUNT> ROLEGROUPACCOUNTs { get; set; }
    }
}
