//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEGROUP
    {
        public string ROLEGROUPID { get; set; }
        public string ROLEGROUPNAME { get; set; }
    }
}
